insert into Deliverable (title, summary, delivery_date, project_id) values ('Ibuprofen', 'consectetuer eget rutrum at lorem integer', '2010-12-11', 11);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Ropinirole', 'dui vel nisl duis ac nibh', '2005-08-10', 10);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Hydrogen Peroxide', 'volutpat convallis morbi odio odio elementum eu interdum', '2011-08-02', 47);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Ibuprofen', 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at', '2003-07-10', 54);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Hydromorphone Hydrochloride', 'diam nam tristique tortor eu pede', '2007-06-07', 56);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Verapamil Hydrochloride', 'aliquet maecenas leo odio condimentum id luctus nec molestie sed', '2021-04-27', 49);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Vita Fresh', 'lorem ipsum dolor sit', '2022-06-06', 61);
insert into Deliverable (title, summary, delivery_date, project_id) values ('NEXIUM', 'lacinia aenean sit amet justo morbi ut', '2024-09-26', 69);
insert into Deliverable (title, summary, delivery_date, project_id) values ('JUNIPERUS VIRGINIANA POLLEN', 'vehicula condimentum curabitur in libero ut massa', '2003-01-20', 65);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Nevi (Mole) Control', 'purus eu magna vulputate luctus cum sociis natoque penatibus et', '2011-07-12', 69);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Nitroglycerin', 'volutpat sapien arcu sed augue aliquam erat volutpat in', '2002-06-06', 33);
insert into Deliverable (title, summary, delivery_date, project_id) values ('HYDROMORPHONE HYDROCHLORIDE', 'quis lectus suspendisse potenti in eleifend quam a', '2004-01-04', 2);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Oxygen', 'eget orci vehicula condimentum curabitur in', '2000-07-26', 22);
insert into Deliverable (title, summary, delivery_date, project_id) values ('NAPRELAN', 'morbi vel lectus in quam fringilla', '2017-12-06', 64);
insert into Deliverable (title, summary, delivery_date, project_id) values ('VALACYCLOVIR HYDROCHLORIDE', 'sociis natoque penatibus et', '2014-11-02', 47);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Ramipril', 'lacinia nisi venenatis tristique', '2022-11-05', 57);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Hydralazine Hydrochloride', 'augue vestibulum ante ipsum primis in faucibus orci luctus', '2023-07-25', 69);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Bio Elm', 'id luctus nec', '2014-01-30', 22);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Womens Dry Eye', 'porta volutpat quam pede lobortis ligula', '2025-06-12', 64);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Levobunolol Hydrochloride', 'rutrum at lorem integer tincidunt ante', '2000-06-29', 10);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Good Sense night time', 'consequat metus sapien ut', '2004-09-24', 31);
insert into Deliverable (title, summary, delivery_date, project_id) values ('INDOCIN', 'ut erat id mauris vulputate elementum', '2013-12-15', 22);
insert into Deliverable (title, summary, delivery_date, project_id) values ('quetiapine fumarate', 'sociis natoque penatibus', '2006-01-18', 59);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Prednisone', 'aenean auctor gravida sem praesent id massa id nisl venenatis', '2001-01-13', 8);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Rutin', 'tincidunt eget tempus vel pede morbi', '2001-09-07', 36);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Nighttime Sleep Aid', 'aenean lectus pellentesque eget nunc donec quis orci', '2020-07-11', 29);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Nicardipine Hydrochloride', 'id justo sit amet sapien dignissim vestibulum vestibulum ante', '2011-10-13', 15);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Cuprum Nicotiana', 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet', '2008-08-07', 34);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Pramipexole Dihydrochloride', 'nulla integer pede justo lacinia eget tincidunt eget', '2003-02-10', 40);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Escitalopram Oxalate', 'erat fermentum justo nec condimentum neque sapien placerat ante', '2007-09-10', 21);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Pravastatin Sodium', 'eu orci mauris lacinia', '2014-07-25', 29);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Doxazosin', 'cubilia curae nulla dapibus dolor vel est donec odio justo', '2001-08-10', 66);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Polibar ACB', 'varius integer ac leo pellentesque ultrices mattis odio', '2004-04-28', 43);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Gablofen', 'porta volutpat quam pede lobortis', '2005-03-15', 15);
insert into Deliverable (title, summary, delivery_date, project_id) values ('dg health sleep aid', 'cum sociis natoque penatibus et magnis', '2013-04-29', 64);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Acne Off Acne Treatment', 'est risus auctor sed tristique in tempus sit amet sem', '2016-04-08', 10);
insert into Deliverable (title, summary, delivery_date, project_id) values ('pain and fever', 'nec dui luctus', '2020-06-05', 66);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Valium', 'turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis', '2019-04-23', 41);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Levothyroxine Sodium', 'nam congue risus semper porta volutpat quam', '2021-05-19', 1);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Original Texture, Orange Flavor', 'ante nulla justo aliquam', '2004-03-18', 68);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Korres Wild Rose Mineral Foundation', 'magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum', '2019-01-08', 29);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Diovan', 'rhoncus dui vel sem sed sagittis nam congue risus', '2011-04-30', 27);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Azasan', 'suspendisse ornare consequat lectus in est risus', '2014-04-09', 62);
insert into Deliverable (title, summary, delivery_date, project_id) values ('PENTOXIFYLLINE', 'urna ut tellus nulla ut erat id', '2020-09-13', 61);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Leader Low Dose Aspirin', 'cursus urna ut tellus nulla ut erat id mauris', '2024-09-20', 34);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Lovastatin', 'in hac habitasse platea dictumst etiam faucibus', '2004-11-01', 53);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Lortab', 'id consequat in consequat ut nulla', '2002-08-05', 13);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Viramune', 'nulla dapibus dolor vel est donec odio justo', '2006-05-21', 42);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Glimepiride', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices', '2010-09-05', 35);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Nighty Nite', 'at nibh in hac habitasse platea dictumst', '2016-01-27', 61);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Zolpidem Tartrate', 'in lectus pellentesque at nulla', '2004-01-05', 31);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Enhance Remedy For Women', 'at nulla suspendisse potenti cras', '2021-04-18', 13);
insert into Deliverable (title, summary, delivery_date, project_id) values ('LACHESIS MUTUS', 'in lacus curabitur at ipsum ac tellus semper', '2023-02-07', 63);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Actoplus Met', 'luctus tincidunt nulla mollis molestie lorem', '2004-07-19', 55);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Time Machine BB', 'sit amet consectetuer adipiscing elit proin interdum mauris non', '2001-05-11', 16);
insert into Deliverable (title, summary, delivery_date, project_id) values ('fungoid tincture', 'ultrices erat tortor', '2007-03-03', 61);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Rifampin', 'in porttitor pede justo', '2013-05-20', 15);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Diclofenac Sodium', 'amet eros suspendisse accumsan tortor quis turpis sed ante', '2020-11-23', 42);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Lansoprazole', 'curae donec pharetra magna vestibulum aliquet ultrices erat', '2006-11-02', 20);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Pulmozyme', 'mi integer ac neque', '2010-08-27', 46);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Timolol Maleate', 'diam id ornare imperdiet sapien urna pretium nisl', '2017-01-31', 40);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Cefadroxil', 'risus praesent lectus vestibulum', '2019-07-04', 21);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Oxygen', 'tempor convallis nulla neque', '2004-12-24', 16);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Sinus Congestion and Pain', 'sapien ut nunc vestibulum ante ipsum primis in faucibus', '2011-05-28', 47);
insert into Deliverable (title, summary, delivery_date, project_id) values ('COLGATE SPARKLING WHITE CINNAMINT', 'ut nulla sed accumsan felis ut at dolor quis odio', '2020-12-12', 64);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Omeprazole', 'sagittis dui vel nisl duis ac nibh', '2010-08-14', 24);
insert into Deliverable (title, summary, delivery_date, project_id) values ('leader mucus er', 'ut nulla sed accumsan', '2023-08-21', 31);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Pacnex', 'ante ipsum primis in faucibus orci luctus', '2011-04-03', 69);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Skelaxin', 'pede malesuada in imperdiet et commodo vulputate justo in blandit', '2009-09-08', 15);
insert into Deliverable (title, summary, delivery_date, project_id) values ('arthricream', 'convallis eget eleifend', '2011-04-10', 10);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Diltiazem Hydrochloride', 'odio curabitur convallis duis consequat dui nec nisi', '2011-10-07', 69);
insert into Deliverable (title, summary, delivery_date, project_id) values ('LEADER ANTIFUNGAL TOLNAFTATE', 'nullam molestie nibh in lectus pellentesque', '2024-07-08', 49);
insert into Deliverable (title, summary, delivery_date, project_id) values ('AVALIDE', 'donec pharetra magna vestibulum', '2014-12-24', 63);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Acne Clear', 'mattis odio donec vitae nisi nam', '2020-09-20', 12);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Etodolac', 'mauris viverra diam vitae', '2022-02-21', 70);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Arnica Rosa', 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien', '2019-07-04', 32);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Potassium Chloride', 'ipsum dolor sit amet consectetuer adipiscing elit proin risus', '2011-08-28', 3);
insert into Deliverable (title, summary, delivery_date, project_id) values ('health mart allergy and congestion', 'aenean auctor gravida', '2000-08-22', 31);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Hill Country Essentials', 'id lobortis convallis tortor risus dapibus augue vel accumsan', '2005-08-31', 19);
insert into Deliverable (title, summary, delivery_date, project_id) values ('leader nose', 'lacus at turpis donec posuere metus vitae ipsum aliquam', '2015-10-01', 39);
insert into Deliverable (title, summary, delivery_date, project_id) values ('DOXOrubicin Hydrochloride', 'congue risus semper porta volutpat quam pede lobortis', '2003-02-17', 31);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Neupro', 'penatibus et magnis dis', '2003-08-07', 63);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Spironolactone', 'vulputate vitae nisl aenean lectus pellentesque', '2019-04-27', 12);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Hydrochlorothiazide', 'cubilia curae duis', '2007-12-11', 15);
insert into Deliverable (title, summary, delivery_date, project_id) values ('TYLENOL Cold', 'ipsum aliquam non mauris morbi non lectus aliquam', '2020-01-02', 35);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Riax', 'mi nulla ac enim', '2008-08-02', 5);
insert into Deliverable (title, summary, delivery_date, project_id) values ('KOCHIA SCOPARIA POLLEN', 'luctus tincidunt nulla mollis', '2000-08-27', 59);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Viscum Echinacea', 'vestibulum proin eu', '2023-09-07', 6);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Renewal Eczema Moisturizing', 'nulla suspendisse potenti cras', '2004-04-05', 32);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Buprenorphine HCl and Naloxone HCl', 'mi sit amet lobortis sapien sapien non', '2027-05-07', 47);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Methocarbamol', 'in blandit ultrices enim', '2021-09-11', 30);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Glipizide and Metformin HCl', 'nonummy maecenas tincidunt', '2004-10-28', 7);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Verapamil Hydrochloride', 'sed tristique in tempus sit', '2001-06-28', 66);
insert into Deliverable (title, summary, delivery_date, project_id) values ('YAT TIP TOR', 'felis sed interdum venenatis turpis enim blandit mi in', '2021-04-29', 63);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Medicated Body Powder', 'molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque', '2000-05-30', 62);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Lotrimin Ultra Jock Itch', 'morbi non lectus aliquam', '2017-11-03', 62);
insert into Deliverable (title, summary, delivery_date, project_id) values ('BOTANICAL VANILLA MAKEUP BASE', 'congue etiam justo etiam pretium iaculis justo', '2004-11-19', 52);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Oxygen', 'velit vivamus vel', '2019-01-04', 69);
insert into Deliverable (title, summary, delivery_date, project_id) values ('oxycodone hydrochloride', 'erat eros viverra eget', '2009-03-02', 4);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Morphine Sulfate', 'vitae quam suspendisse potenti nullam porttitor lacus', '2027-04-26', 55);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Healerz for Itches', 'accumsan felis ut at dolor quis odio consequat varius integer', '2018-06-10', 15);
insert into Deliverable (title, summary, delivery_date, project_id) values ('smart sense 7 day treatment', 'libero convallis eget eleifend', '2002-04-11', 44);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Sulfamethoxazole and Trimethoprim', 'nulla sed vel enim sit amet nunc', '2023-08-21', 37);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Alprazolam', 'blandit non interdum in ante vestibulum ante ipsum', '2005-01-11', 53);
insert into Deliverable (title, summary, delivery_date, project_id) values ('GEMCITABINE HYDROCHLORIDE', 'tempus semper est quam pharetra magna ac consequat metus', '2008-02-19', 67);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Hot Ice Soothing Analgesic Gel', 'sapien a libero nam', '2016-02-29', 28);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Viagra', 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum', '2005-12-19', 2);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Total Body Detox', 'amet diam in magna bibendum imperdiet nullam orci pede venenatis', '2000-11-04', 23);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Thyreoidea Belladonna', 'non mauris morbi non lectus', '2023-02-08', 29);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Degree', 'eget nunc donec quis orci eget orci vehicula condimentum curabitur', '2007-10-26', 21);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Solodyn', 'ut erat id mauris vulputate elementum nullam varius', '2011-08-27', 64);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Venlafaxine Hydrochloride', 'bibendum morbi non quam nec dui', '2007-12-11', 27);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Glyburide', 'in leo maecenas pulvinar lobortis', '2006-01-10', 6);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Cartia', 'turpis enim blandit mi in porttitor pede justo', '2020-11-11', 64);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Benztropine Mesylate', 'dui maecenas tristique est et tempus semper est quam', '2024-06-18', 69);
insert into Deliverable (title, summary, delivery_date, project_id) values ('PREVPAC', 'sit amet turpis elementum ligula vehicula consequat morbi a', '2001-10-22', 65);
insert into Deliverable (title, summary, delivery_date, project_id) values ('DentiCare Pro-Gel', 'volutpat quam pede lobortis ligula sit amet eleifend pede', '2015-11-19', 33);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Weed and Grass Antigen', 'blandit ultrices enim lorem ipsum', '2014-12-03', 21);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Cleviprex', 'hac habitasse platea', '2009-09-12', 60);
insert into Deliverable (title, summary, delivery_date, project_id) values ('ibuprofen', 'quam sollicitudin vitae', '2011-03-18', 2);
insert into Deliverable (title, summary, delivery_date, project_id) values ('sunmark lice solution kit', 'augue a suscipit', '2021-04-04', 1);
insert into Deliverable (title, summary, delivery_date, project_id) values ('fexofenadine hydrochloride', 'tincidunt ante vel ipsum praesent blandit', '2004-09-29', 3);
insert into Deliverable (title, summary, delivery_date, project_id) values ('INVOKANA', 'velit id pretium iaculis', '2005-07-31', 59);
insert into Deliverable (title, summary, delivery_date, project_id) values ('ACER NEGUNDO POLLEN', 'vehicula condimentum curabitur in libero ut massa volutpat convallis', '2005-05-27', 38);
insert into Deliverable (title, summary, delivery_date, project_id) values ('METAXALONE', 'duis bibendum felis sed interdum venenatis turpis enim', '2014-10-04', 58);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Flumazenil', 'id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum', '2015-04-30', 12);
insert into Deliverable (title, summary, delivery_date, project_id) values ('D-TOX Remedy', 'ipsum aliquam non mauris morbi non lectus aliquam sit amet', '2011-12-03', 46);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Bone Repair', 'est quam pharetra magna ac', '2021-07-11', 5);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Olay Regenerist', 'tortor quis turpis sed ante vivamus tortor', '2020-08-01', 38);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Keflex', 'justo nec condimentum neque sapien placerat ante', '2004-08-29', 24);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Diabet Aid', 'dictumst aliquam augue quam', '2026-01-08', 2);
insert into Deliverable (title, summary, delivery_date, project_id) values ('ropinirole', 'vel lectus in quam fringilla rhoncus mauris enim leo', '2025-09-15', 28);
insert into Deliverable (title, summary, delivery_date, project_id) values ('NOTUSS', 'in leo maecenas pulvinar lobortis est phasellus sit amet', '2006-07-12', 62);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Griseofulvin', 'velit eu est congue elementum in', '2020-10-28', 40);
insert into Deliverable (title, summary, delivery_date, project_id) values ('ANTIBACTERIAL HAND SOAP', 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien', '2027-01-20', 22);
insert into Deliverable (title, summary, delivery_date, project_id) values ('COMPLERA', 'mi in porttitor pede justo eu', '2001-07-01', 24);
