insert into Program (program_id, program_name, management) values (1, 'Furniss'' Pincushionplant', 'Accounting');
insert into Program (program_id, program_name, management) values (2, 'Wild Indigo', 'Support');
insert into Program (program_id, program_name, management) values (3, 'Santa Barbara Milkvetch', 'Services');
insert into Program (program_id, program_name, management) values (4, 'Hybrid Violet', 'Product Management');
insert into Program (program_id, program_name, management) values (5, 'Breadfruit', 'Human Resources');
insert into Program (program_id, program_name, management) values (6, 'Desert Columbine', 'Services');
insert into Program (program_id, program_name, management) values (7, 'Parsley Fern', 'Marketing');
insert into Program (program_id, program_name, management) values (8, 'Dawn Redwood', 'Sales');
insert into Program (program_id, program_name, management) values (9, 'Pinnate False Threadleaf', 'Marketing');
insert into Program (program_id, program_name, management) values (10, 'Western Dwarf Cliffbrake', 'Marketing');
insert into Program (program_id, program_name, management) values (11, 'Hobdy''s Woodfern', 'Human Resources');
insert into Program (program_id, program_name, management) values (12, 'Littleleaf Milkwort', 'Product Management');
insert into Program (program_id, program_name, management) values (13, 'Fissidens Moss', 'Human Resources');
insert into Program (program_id, program_name, management) values (14, 'Littleflower Alumroot', 'Services');
insert into Program (program_id, program_name, management) values (15, 'Eccremidium Moss', 'Business Development');
insert into Program (program_id, program_name, management) values (16, 'Gyroweisia Moss', 'Business Development');
insert into Program (program_id, program_name, management) values (17, 'Silverweed', 'Accounting');
insert into Program (program_id, program_name, management) values (18, 'San Bernardino Suncup', 'Accounting');
insert into Program (program_id, program_name, management) values (19, 'Bird''s-eye Bush', 'Training');
insert into Program (program_id, program_name, management) values (20, 'Barberry', 'Marketing');
insert into Program (program_id, program_name, management) values (21, 'Limestone Maiden Fern', 'Human Resources');
insert into Program (program_id, program_name, management) values (22, 'Stiffstem Flax', 'Services');
insert into Program (program_id, program_name, management) values (23, 'Smallflowered Milkvetch', 'Product Management');
insert into Program (program_id, program_name, management) values (24, 'Q-tips', 'Training');
insert into Program (program_id, program_name, management) values (25, 'Goldenbush', 'Accounting');
insert into Program (program_id, program_name, management) values (26, 'Rosy Bird''s-foot Trefoil', 'Research and Development');
insert into Program (program_id, program_name, management) values (27, 'Hedwigia Moss', 'Human Resources');
insert into Program (program_id, program_name, management) values (28, 'Cold Crabseye Lichen', 'Services');
insert into Program (program_id, program_name, management) values (29, 'Marijuana', 'Legal');
insert into Program (program_id, program_name, management) values (30, 'Coastal Monkeyflower', 'Human Resources');
insert into Program (program_id, program_name, management) values (31, 'Cafe Falso', 'Training');
insert into Program (program_id, program_name, management) values (32, 'Kaibab Suncup', 'Accounting');
insert into Program (program_id, program_name, management) values (33, 'Dactylospora Lichen', 'Business Development');
insert into Program (program_id, program_name, management) values (34, 'Mancos Shadscale', 'Human Resources');
insert into Program (program_id, program_name, management) values (35, 'Whitney''s False Oat', 'Support');
insert into Program (program_id, program_name, management) values (36, 'Babington''s Graphina Lichen', 'Legal');
insert into Program (program_id, program_name, management) values (37, 'Fairybells', 'Support');
insert into Program (program_id, program_name, management) values (38, 'Bristle Bent', 'Engineering');
insert into Program (program_id, program_name, management) values (39, 'Gray''s Townsend Daisy', 'Human Resources');
insert into Program (program_id, program_name, management) values (40, 'Sierra Erigeron', 'Product Management');
insert into Program (program_id, program_name, management) values (41, 'Moxley''s Dry Rock Moss', 'Training');
insert into Program (program_id, program_name, management) values (42, 'Hornwort', 'Engineering');
insert into Program (program_id, program_name, management) values (43, 'Faurie''s Cyanea', 'Support');
insert into Program (program_id, program_name, management) values (44, 'Louisiana Goldenrod', 'Support');
insert into Program (program_id, program_name, management) values (45, 'Fern-leaved Monkeyflower', 'Marketing');
insert into Program (program_id, program_name, management) values (46, 'Eastwood''s Milkvetch', 'Research and Development');
insert into Program (program_id, program_name, management) values (47, 'Gregorywood', 'Research and Development');
insert into Program (program_id, program_name, management) values (48, 'Fishscale Lichen', 'Support');
insert into Program (program_id, program_name, management) values (49, 'Manatee Mudflower', 'Engineering');
insert into Program (program_id, program_name, management) values (50, 'Rosea', 'Accounting');
